Update devserver dockerfile to matchh changed skdb-base
SkipLabs/skdb pull request #85
Opened 2024-01-29 16:39 UTC by bennostein

Use renamed base image, and drop no-op copy which was causing errors.

2024-01-29 17:10 UTC, bennostein commented
I've pushed latest+quickstart versions of skdb-base and skdb-dev-server using thesse changes, and NPM packages to match.  Everything seems good on my end, but shout if that's broken you.

2024-01-30 10:31 UTC, gregsexton requested changes

2024-01-30 10:31 UTC, gregsexton commented on sql/server/dev/Dockerfile
> -COPY --from=skdb /skdb/build ./build
We need skdb/build for the skdb binary that the dev server uses. Without this we don't have the binary.

2024-01-30 10:31 UTC, gregsexton commented on sql/server/dev/Dockerfile
> +FROM skiplabs/skdb-base as skdb
This should be skiplabs/skdb which builds on skiplabs/skdb-base. The dockerfile for this is in sql/Dockerfile. I refactored to make building for prod possible. I think I might have missed updating a script that needs to build this for the dev server?

2024-01-30 10:33 UTC, gregsexton commented
I imagine the dev server you built and pushed doesn't work if you try to connect to it?

2024-01-30 13:04 UTC, bennostein commented
Yes, you're right.  I think I jumped the gun here with these changes after running into some unrelated issues building a new devserver image yesterday.  Will investigate further, closing this one now.

2024-01-30 13:04 UTC, closed without merging